export const Images = {
    tabs: {
        Home: require('../../assets/tab/loan.png'),
        HomeSelected: require('../../assets/tab/loan-selected.png'),
        Bill: require('../../assets/tab/bill.png'),
        BillSelected: require('../../assets/tab/bill-selected.png'),
        Account: require('../../assets/tab/account.png'),
        AccountSelected: require('../../assets/tab/account-selected.png'),
    },
    my: {
        IconAvatar:require('../../assets/account/avatar.png'),
        Avatar:require('../../assets/myscreen/my_bank.png'),
        Auth:require('../../assets/my/verified.png'),
        NoAuth:require('../../assets/my/noverified.png'),
        NoAuthDialog:require('../../assets/my/no-auth.png'),
        Bank: require('../../assets/my/my_bank.png'),
        Record: require('../../assets/my/apply_log.png'),
        Help: require('../../assets/my/help_center.png'),
        About: require('../../assets/my/about_us.png'),
        Setting: require('../../assets/my/setup.png'),
        CustomerBg: require('../../assets/my/service_bg.png'),
        CustomerBtn: require('../../assets/my/service_button.png'),
    },
    home: {
        BtnPrimary: require('../../assets/home/button_back.png'),
        BtnGray: require('../../assets/home/button_no_back.png'),
        Logo: require('../../assets/homescreen/logo_home.png'),
        IconMsg: require('../../assets/homescreen/message_home.png'),
        Banner: require('../../assets/homescreen/banner_home.png'),
    },
    auth: {
        Logo: require('../../assets/common/img-logo.png'),
        CheckBoxImg: require('../../assets/common/img-checkbox.png'),
        CheckBoxedImg: require('../../assets/common/img-checkbox-active.png'),

        ImgCertFront: require('../../assets/common/img-cert-front.png'),
        ImgCertBack: require('../../assets/common/img-cert-back.png'),
        IconPerson: require('../../assets/auth/img-person.png'),

        Alipay: require('../../assets/auth/alipay.png'),
        Weixin: require('../../assets/auth/weixin.png'),
        IncomeMoney: require('../../assets/auth/income_money.png'),
        DebtMessage: require('../../assets/auth/debt_message.png'),
        Negative: require('../../assets/auth/negative.png'),
        ShopCart: require('../../assets/auth/shop_cart.png'),
        Other: require('../../assets/auth/other.png'),

        ImgBack: require('../../assets/authall/img_back.png'),
        Name: require('../../assets/authall/name.png'),
        Work: require('../../assets/authall/work.png'),
        Identify: require('../../assets/authall/identify.png'),
        Basic: require('../../assets/authall/basic.png'),

    },
    bill: {
        null: require('../../assets/bill/bill-null.png'),
        PayResult: require('../../assets/common/img-pay-result.png'),
        PayResult1: require('../../assets/bill/img-bill-pay-result.png'),
        LoanBg: require('../../assets/common/img-loan-bg.png'),
        LoanResult: require('../../assets/common/img-loan-result.png'),
        LoanIng: require('../../assets/bill/loan-ing.png'),
        PaySure: require('../../assets/paysurescreen/pay_sure.png'),
        BillDetailBg: require('../../assets/bill/bill-detail-header.png'),
        CheckNull: require('../../assets/bill/bill-check-null.png'),
        Checked: require('../../assets/bill/bill-check-select.png'),
    },
    cashier: {
        PayWx: require('../../assets/cashier/paywx.png'),
        Close: require('../../assets/cashier/close.png'),
        PayCard: require('../../assets/cashier/payCard.png'),
        PayChange: require('../../assets/cashier/payChange.png'),
        payChooseNull: require('../../assets/cashier/chooseNull.png'),
        payChoosed: require('../../assets/cashier/choosed.png'),
    },
    bank: {
        Null: require('../../assets/mybank/bank-null.png'),
        add: require('../../assets/mybank/mybank_add.png'),
        Iright: require('../../assets/public/bank_icon_right.png'),
        // 银行卡icon BJB SHB
        ICBC: require('../../assets/bankicon/gs.png'),
        SHB: require('../../assets/bankicon/gd.png'),
        GDB: require('../../assets/bankicon/gf.png'),
        HXB: require('../../assets/bankicon/hx.png'),
        CCB: require('../../assets/bankicon/js.png'),
        COMM: require('../../assets/bankicon/jt.png'),
        IconMs: require('../../assets/bankicon/ms.png'),
        ABC: require('../../assets/bankicon/ny.png'),
        PINAGAN: require('../../assets/bankicon/pa.png'),
        SPDB: require('../../assets/bankicon/pf.png'),
        CIB: require('../../assets/bankicon/xy.png'),
        PSBC: require('../../assets/bankicon/yz.png'),
        BOC: require('../../assets/bankicon/zg.png'),
        CMB: require('../../assets/bankicon/zs.png'),
        CITIC: require('../../assets/bankicon/zx.png'),
    },
    loan: {
        Null: require('../../assets/common/loan-record-null.png'),
        
        Tips: require('../../assets/common/img-loan-tips.png'),
        Help: require('../../assets/common/img-loan-help.png'),
        CommonClose: require('../../assets/common/close.png'),
        Cellarrow: require('../../assets/public/cell_arrow.png'),
        sign: require('../../assets/signscreen/sign_write.png'),
    },
    authname:{
        Idfront: require('../../assets/authnamescreen/id_front.png'),
        Idreverse: require('../../assets/authnamescreen/id_reverse.png'),
        Normal: require('../../assets/authnamescreen/normal_scan.png'),
        RightIcon: require('../../assets/authnamescreen/right_icon.png'),
        BorderMiss: require('../../assets/authnamescreen/border_miss.png'),
        WrongIcon: require('../../assets/authnamescreen/wrong_icon.png'),
        PhotoBlurry: require('../../assets/authnamescreen/photo_blurry.png'),
        StrongFlash: require('../../assets/authnamescreen/strong_flash.png'),
        DialogClose: require('../../assets/authnamescreen/auth-close.png'),
    },
    public:{
        success: require('../../assets/public/success.png'),
        notice: require('../../assets/public/notice.png'),
        closeBlack: require('../../assets/public/close_black.png'),
        selectActive: require('../../assets/public/select_active.png'),
        selectNoActive: require('../../assets/public/select.png'),
        addContact: require('../../assets/basicscreen/add_user.png'),
        SafeAuth: require('../../assets/basicscreen/safe_auth.png'),
        Sicon: require('../../assets/public/student_icon.png'),
        Testlogo:require('../../assets/myscreen/avatar.png'),
        Search:require('../../assets/loanscreen/search_icon.png'),
        Delete:require('../../assets/public/delete_icon.png'),
    },
    login:{
        Logo:require('../../assets/login/logo.png'),
    }
};

